export type TrackType = '육상트랙' | '한강코스' | '공원코스' | '산악코스';

export interface RunningSpot {
  id: string;
  name: string;
  type: TrackType;
  lat: number;
  lng: number;
  distanceKm?: number;
  surface?: string;
  note?: string;
  hours?: string;      // 운영시간
  fee?: string;        // 이용 요금 (없으면 무료)
  accessible: boolean;
}

export const RUNNING_SPOTS: RunningSpot[] = [
  // ── 육상 트랙 (400m 공식) ──
  {
    id: 'jamsil-aux',
    name: '잠실보조경기장',
    type: '육상트랙',
    lat: 37.5118, lng: 127.0741,
    distanceKm: 0.4, surface: 'tartan',
    note: '서울 대표 공개 트랙',
    hours: '06:00 – 22:00',
    fee: '무료',
    accessible: true,
  },
  {
    id: 'mokdong',
    name: '목동종합운동장 트랙',
    type: '육상트랙',
    lat: 37.5280, lng: 126.8750,
    distanceKm: 0.4, surface: 'tartan',
    hours: '06:00 – 22:00',
    fee: '1,000원/회',
    accessible: true,
  },
  {
    id: 'worldcup-aux',
    name: '서울월드컵경기장 보조경기장',
    type: '육상트랙',
    lat: 37.5696, lng: 126.8975,
    distanceKm: 0.4, surface: 'tartan',
    note: '상암동',
    hours: '06:00 – 22:00',
    fee: '무료',
    accessible: true,
  },
  {
    id: 'olympic-stadium-aux',
    name: '올림픽공원 육상경기장',
    type: '육상트랙',
    lat: 37.5178, lng: 127.1222,
    distanceKm: 0.4, surface: 'tartan',
    note: '올림픽공원 내',
    hours: '09:00 – 18:00',
    fee: '공원 입장료 별도',
    accessible: true,
  },
  {
    id: 'dongdaemun',
    name: '동대문구 육상경기장',
    type: '육상트랙',
    lat: 37.5774, lng: 127.0432,
    distanceKm: 0.4, surface: 'tartan',
    hours: '06:00 – 22:00',
    fee: '무료',
    accessible: true,
  },
  {
    id: 'mapo',
    name: '마포구민체육센터 트랙',
    type: '육상트랙',
    lat: 37.5486, lng: 126.9129,
    distanceKm: 0.4, surface: 'tartan',
    hours: '06:00 – 22:00',
    fee: '무료',
    accessible: true,
  },
  {
    id: 'jungnang-track',
    name: '중랑천 체육공원 트랙',
    type: '육상트랙',
    lat: 37.5790, lng: 127.0760,
    distanceKm: 0.4, surface: 'tartan',
    note: '중랑천변',
    hours: '상시 개방',
    fee: '무료',
    accessible: true,
  },
  {
    id: 'banpo-stadium',
    name: '반포종합운동장 트랙',
    type: '육상트랙',
    lat: 37.5038, lng: 126.9993,
    distanceKm: 0.4, surface: 'tartan',
    note: '반포한강공원 인근',
    hours: '06:00 – 22:00',
    fee: '무료',
    accessible: true,
  },
  {
    id: 'yangcheon',
    name: '양천구 목동 보조트랙',
    type: '육상트랙',
    lat: 37.5306, lng: 126.8698,
    distanceKm: 0.4, surface: 'tartan',
    note: '안양천변',
    hours: '06:00 – 22:00',
    fee: '무료',
    accessible: true,
  },
  {
    id: 'seongdong',
    name: '성동구 체육관 트랙',
    type: '육상트랙',
    lat: 37.5639, lng: 127.0378,
    distanceKm: 0.4, surface: 'tartan',
    note: '중랑천 서쪽, 행당동',
    hours: '06:00 – 22:00',
    fee: '무료',
    accessible: true,
  },

  // ── 한강 러닝 코스 ──
  {
    id: 'hangang-yeouido',
    name: '여의도 한강공원 코스',
    type: '한강코스',
    lat: 37.5283, lng: 126.9332,
    distanceKm: 7.0,
    note: '여의도 일주 약 7km, 평탄 포장',
    hours: '상시 개방',
    fee: '무료',
    accessible: true,
  },
  {
    id: 'hangang-ttukseom',
    name: '뚝섬 한강공원 코스',
    type: '한강코스',
    lat: 37.5311, lng: 127.0687,
    distanceKm: 5.5,
    note: '성수대교~잠실대교, 야경 명소',
    hours: '상시 개방',
    fee: '무료',
    accessible: true,
  },
  {
    id: 'hangang-jamsil',
    name: '잠실 한강공원 코스',
    type: '한강코스',
    lat: 37.5173, lng: 127.0921,
    distanceKm: 4.0,
    hours: '상시 개방',
    fee: '무료',
    accessible: true,
  },
  {
    id: 'hangang-banpo',
    name: '반포 한강공원 코스',
    type: '한강코스',
    lat: 37.5106, lng: 126.9971,
    distanceKm: 5.0,
    note: '반포대교 무지개분수 구간',
    hours: '상시 개방',
    fee: '무료',
    accessible: true,
  },
  {
    id: 'hangang-mangwon',
    name: '망원 한강공원 코스',
    type: '한강코스',
    lat: 37.5498, lng: 126.9057,
    distanceKm: 4.5,
    hours: '상시 개방',
    fee: '무료',
    accessible: true,
  },

  // ── 공원 코스 ──
  {
    id: 'olympic-park',
    name: '올림픽공원 일주로',
    type: '공원코스',
    lat: 37.5204, lng: 127.1224,
    distanceKm: 5.6,
    note: '포장 일주로, 송파구 대표 코스',
    hours: '상시 개방',
    fee: '무료',
    accessible: true,
  },
  {
    id: 'seoul-forest',
    name: '서울숲 코스',
    type: '공원코스',
    lat: 37.5474, lng: 127.0375,
    distanceKm: 3.0,
    note: '뚝섬역 인근, 그늘 코스',
    hours: '상시 개방',
    fee: '무료',
    accessible: true,
  },
  {
    id: 'boramae',
    name: '보라매공원 코스',
    type: '공원코스',
    lat: 37.4938, lng: 126.9230,
    distanceKm: 2.5,
    note: '신대방역 인근',
    hours: '상시 개방',
    fee: '무료',
    accessible: true,
  },
  {
    id: 'bukseoul',
    name: '북서울꿈의숲 코스',
    type: '공원코스',
    lat: 37.6200, lng: 127.0526,
    distanceKm: 3.5,
    note: '창동·방학 인근, 언덕 있음',
    hours: '상시 개방',
    fee: '무료',
    accessible: true,
  },
  {
    id: 'worldcup-park',
    name: '월드컵공원(노을공원) 코스',
    type: '공원코스',
    lat: 37.5684, lng: 126.8973,
    distanceKm: 4.0,
    note: '능선 코스, 경사 있음',
    hours: '상시 개방',
    fee: '무료',
    accessible: true,
  },
  {
    id: 'seonjeongneung',
    name: '선릉·정릉 코스',
    type: '공원코스',
    lat: 37.5087, lng: 127.0469,
    distanceKm: 2.0,
    note: '역삼 인근, 흙길 포함',
    hours: '06:00 – 21:00',
    fee: '무료 (문화재구역 무료)',
    accessible: true,
  },

  // ── 산악 코스 ──
  {
    id: 'namsan',
    name: '남산 순환 코스',
    type: '산악코스',
    lat: 37.5512, lng: 126.9882,
    distanceKm: 6.8,
    note: '순환 포장도로, 경사 있음',
    hours: '상시 개방',
    fee: '무료',
    accessible: true,
  },
  {
    id: 'bukhansan-ui',
    name: '북한산 우이령 코스',
    type: '산악코스',
    lat: 37.6587, lng: 126.9906,
    distanceKm: 6.8,
    note: '사전 예약 필요 (국립공원)',
    hours: '07:00 – 15:00',
    fee: '무료 (예약 필수)',
    accessible: true,
  },
  {
    id: 'acha-mountain',
    name: '아차산 둘레길',
    type: '산악코스',
    lat: 37.5543, lng: 127.1051,
    distanceKm: 5.0,
    note: '광진구, 흙길 위주',
    hours: '상시 개방',
    fee: '무료',
    accessible: true,
  },
];

export const TRACK_TYPE_CONFIG: Record<TrackType, { color: string; lucideIcon: string; label: string }> = {
  '육상트랙': { color: '#7c3aed', lucideIcon: 'CirclePlay', label: '육상 트랙' },
  '한강코스': { color: '#0ea5e9', lucideIcon: 'Waves',      label: '한강 코스' },
  '공원코스': { color: '#22c55e', lucideIcon: 'Trees',      label: '공원 코스' },
  '산악코스': { color: '#f97316', lucideIcon: 'Mountain',   label: '산악 코스' },
};
